- name: Install Jenkins
  hosts: ci-server
  vars_files:
    - plugin_list_jenkins.yml
  connection: local
  become: yes
  become_method: sudo
  tasks:

    - name: Download Jenkins repo
      tags: first_run
      get_url:
        url: http://pkg.jenkins-ci.org/redhat/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

    - name: Install Jenkins repo key
      tags: first_run
      rpm_key:
        state: present
        key: http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key

    - name: Install Jenkins
      tags: first_run
      yum:
        name: jenkins
        state: latest

    - name: Start Jenkins
      tags: first_run
      service:
        name: jenkins
        state: started

    - name: Download jenkins-cli.jar
      tags: first_run
      get_url:
        url: https://{{ inventory_hostname }}.davenport.edu/jnlpJars/jenkins-cli.jar
        dest: /var/lib/jenkins
        mode: 0664

    - name: Install plugins
      tags: second_run
      become: yes
      become_user: jenkins
      command: java -jar /var/lib/jenkins/jenkins-cli.jar -s https://{{ inventory_hostname }}.davenport.edu -ssh -user jenkins -i /var/lib/jenkins/.ssh/id_rsa install-plugin {{ jenkins_plugins }} -deploy -restart
