jenkins_plugins:
  maven-plugin
  javadoc
  jenkinslint
  mercurial
  external-monitor-job
  credentials
  windows-slaves
  slack
  workflow-step-api
  display-url-api
  ansicolor
  cas-plugin
  token-macro
  antisamy-markup-formatter
  translation
  ldap
  junit
  cvs
  command-launcher
  icon-shim
  bouncycastle-api
  matrix-auth
  matrix-project
  ssh-slaves
  mapdb-api
  jsch
  scm-api
  subversion
  pam-auth
  ant
  script-security
  ssh-credentials
  structs
  email-ext
  mailer
  Exclusion
  git-client
  git
  github
  git-branch-source
  jackson2-api
  plain-credentials
  rake
  ruby-runtime
  rvm
  workflow-scm-step
  workflow-support
  workflow-api
  apache-httpcomponents-client-4-api
  workflow-job
